/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Classes/Class.java to edit this template
 */
package com.posta.NuevoPosta.Enums;

/**
 *
 * @author crowl
 */
public enum Actividades {

    ASALARIADOS("0010", "Asalariados"),
    PERSONAS_NATURALES_SIN_ACTIVIDAD("0081", "Personas Naturales sin Actividad Económica"),
    PERSONAS_NATURALES_SUBSIDIADAS("0082", "Personas Naturales Subsidiadas por Terceros"),
    RENTISTAS_DE_CAPITAL("0090", "Rentistas de Capital, solo para personas naturales."),
    CULTIVO_DE_CEREALES("0111", "Cultivo de cereales (excepto arroz), legumbres y semillas oleaginosas."),
    CULTIVO_DE_ARROZ("0112", "Cultivo de arroz."),
    CULTIVO_DE_HORTALIZAS("0113", "Cultivo de hortalizas, raíces y tubérculos."),
    CULTIVO_DE_TABACO("0114", "Cultivo de tabaco."),
    CULTIVO_DE_PLANTAS_TEXTILES("0115", "Cultivo de plantas textiles."),
    OTROS_CULTIVOS_TRANSITORIOS("0119", "Otros cultivos transitorios n.c.p."),
    CULTIVO_DE_FRUTAS_TROPICALES("0121", "Cultivo de frutas tropicales y subtropicales."),
    CULTIVO_DE_PLATANO("0122", "Cultivo de plátano y banano."),
    CULTIVO_DE_CAFE("0123", "Cultivo de café."),
    CULTIVO_DE_CANNA_DE_AZUCAR("0124", "Cultivo de caña de azúcar."),
    CULTIVO_DE_FLOR_DE_CORTE("0125", "Cultivo de flor de corte."),
    CULTIVO_DE_PALMA_PARA_ACEITE("0126", "Cultivo de palma para aceite (palma africana) y otros frutos oleaginosos."),
    CULTIVO_DE_PLANTAS_BEBIDAS("0127", "Cultivo de plantas con las que se preparan bebidas."),
    CULTIVO_DE_ESPECIAS("0128", "Cultivo de especias y de plantas aromáticas y medicinales."),
    OTROS_CULTIVOS_PERMANENTES("0129", "Otros cultivos permanentes n.c.p."),
    PROPAGACION_DE_PLANTAS("0130", "Propagación de plantas (actividades de los viveros, excepto viveros forestales)."),
    CRIA_DE_GANADO_BOVINO("0141", "Cría de ganado bovino y bufalino."),
    CRIA_DE_CABALLOS("0142", "Cría de caballos y otros equinos."),
    CRIA_DE_OVEJAS_Y_CABRAS("0143", "Cría de ovejas y cabras."),
    CRIA_DE_GANADO_PORCINO("0144", "Cría de ganado porcino."),
    CRIA_DE_AVES_DE_CORRAL("0145", "Cría de aves de corral."),
    CRIA_DE_OTROS_ANIMALES("0149", "Cría de otros animales n.c.p."),
    EXPLOTACION_MIXTA("0150", "Explotación mixta (agrícola y pecuaria)."),
    ACTIVIDADES_APOYO_AGRICULTURA("0161", "Actividades de apoyo a la agricultura."),
    ACTIVIDADES_APOYO_GANADERIA("0162", "Actividades de apoyo a la ganadería."),
    ACTIVIDADES_POSTERIORES_COSECHA("0163", "Actividades posteriores a la cosecha."),
    TRATAMIENTO_SEMILLAS("0164", "Tratamiento de semillas para propagación."),
    CAZA_ORDINARIA("0170", "Caza ordinaria y mediante trampas y actividades de servicios conexas."),
    SILVICULTURA("0210", "Silvicultura y otras actividades forestales."),
    EXTRACCION_DE_MADERA("0220", "Extracción de madera."),
    RECOLECCION_PRODUCTOS_FORESTALES("0230", "Recolección de productos forestales diferentes a la madera."),
    SERVICIOS_APOYO_SILVICULTURA("0240", "Servicios de apoyo a la silvicultura."),
    PESCA_MARITIMA("0311", "Pesca marítima."),
    PESCA_AGUA_DULCE("0312", "Pesca de agua dulce."),
    ACUICULTURA_MARITIMA("0321", "Acuicultura marítima."),
    ACUICULTURA_AGUA_DULCE("0322", "Acuicultura de agua dulce."),
    EXTRACCION_HULLA("0510", "Extracción de hulla (carbón de piedra)."),
    EXTRACCION_CARBO_LIGNITO("0520", "Extracción de carbón lignito."),
    EXTRACCION_PETROLEO_CRUDO("0610", "Extracción de petróleo crudo."),
    EXTRACCION_GAS_NATURAL("0620", "Extracción de gas natural."),
    EXTRACCION_MINERALES_HIERRO("0710", "Extracción de minerales de hierro."),
    EXTRACCION_MINERALES_URANIO("0721", "Extracción de minerales de uranio y de torio."),
    EXTRACCION_ORO("0722", "Extracción de oro y otros metales preciosos."),
    EXTRACCION_MINERALES_NIQUEL("0723", "Extracción de minerales de níquel."),
    EXTRACCION_OTROS_MINERALES("0729", "Extracción de otros minerales metalíferos no ferrosos n.c.p."),
    EXTRACCION_PIEDRA_ARENA("0811", "Extracción de piedra, arena, arcillas comunes, yeso y anhidrita."),
    EXTRACCION_ARCILLAS("0812", "Extracción de arcillas de uso industrial, caliza, caolín y bentonitas."),
    EXTRACCION_ESMERALDAS("0820", "Extracción de esmeraldas, piedras preciosas y semipreciosas."),
    EXTRACCION_MINERALES_ABONOS("0891", "Extracción de minerales para la fabricación de abonos y productos químicos."),
    EXTRACCION_HALITA("0892", "Extracción de halita (sal)."),
    EXTRACCION_OTROS_MINERALES_1("0899", "Extracción de otros minerales no metálicos n.c.p."),
    ACTIVIDADES_APOYO_PETROLEO_GAS("0910", "Actividades de apoyo para la extracción de petróleo y de gas natural."),
    ACTIVIDADES_APOYO_MINERAS("0990", "Actividades de apoyo para otras actividades de explotación de minas y canteras."),
    PROCESAMIENTO_CARNE("1011", "Procesamiento y conservación de carne y productos cárnicos."),
    PROCESAMIENTO_PESCADOS("1012", "Procesamiento y conservación de pescados, crustáceos y moluscos."),
    PROCESAMIENTO_FRUTAS("1020", "Procesamiento y conservación de frutas, legumbres, hortalizas y tubérculos."),
    ELABORACION_ACEITES("1030", "Elaboración de aceites y grasas de origen vegetal y animal."),
    ELABORACION_LACTEOS("1040", "Elaboración de productos lácteos."),
    ELABORACION_MOLINERIA("1051", "Elaboración de productos de molinería."),
    ELABORACION_ALMIDONES("1052", "Elaboración de almidones y productos derivados del almidón."),
    TRILLA_CAFE("1061", "Trilla de café."),
    DESCAFEINADO_CAFE("1062", "Descafeinado, tostión y molienda del café."),
    OTROS_DERIVADOS_CAFE("1063", "Otros derivados del café."),
    ELABORACION_REFINACION_AZUCAR("1071", "Elaboración y refinación de azúcar."),
    ELABORACION_PANELA("1072", "Elaboración de panela."),
    ELABORACION_PANADERIA("1081", "Elaboración de productos de panadería."),
    ELABORACION_CACAO("1082", "Elaboración de cacao, chocolate y productos de confitería."),
    ELABORACION_MACARRONES("1083", "Elaboración de macarrones, fideos, alcuzcuz y productos farináceos similares."),
    ELABORACION_COMIDAS_PREPARADAS("1084", "Elaboración de comidas y platos preparados."),
    ELABORACION_OTROS_PRODUCTOS("1089", "Elaboración de otros productos alimenticios n.c.p."),
    ELABORACION_ALIMENTOS_ANIMALES("1090", "Elaboración de alimentos preparados para animales."),
    DESTILACION_BEBIDAS_ALCOHOLICAS("1101", "Destilación, rectificación y mezcla de bebidas alcohólicas."),
    ELABORACION_BEBIDAS_FERMENTADAS("1102", "Elaboración de bebidas fermentadas no destiladas."),
    PRODUCCION_MALTA("1103", "Producción de malta, elaboración de cervezas y otras bebidas malteadas."),
    ELABORACION_BEBIDAS_NO_ALCOHOLICAS("1104", "Elaboración de bebidas no alcohólicas, producción de aguas minerales y de otras aguas embotelladas."),
    ELABORACION_TABACO("1200", "Elaboración de productos de tabaco."),
    PREPARACION_FIBRAS_TEXTILES("1311", "Preparación e hilatura de fibras textiles."),
    TEJEDURIA_TEXTILES("1312", "Tejeduría de productos textiles."),
    ACABADO_TEXTILES("1313", "Acabado de productos textiles."),
    FABRICACION_TEJIDOS_PUNTO("1391", "Fabricación de tejidos de punto y ganchillo."),
    CONFECCION_ARTICULOS_TEXTILES("1392", "Confección de artículos con materiales textiles, excepto prendas de vestir."),
    FABRICACION_TAPETES_ALFOMBRAS("1393", "Fabricación de tapetes y alfombras para pisos."),
    FABRICACION_CUERDAS_CORDELES("1394", "Fabricación de cuerdas, cordeles, cables, bramantes y redes."),
    FABRICACION_PRENDAS_VESTIR("1410", "Confección de prendas de vestir, excepto prendas de piel."),
    FABRICACION_ARTICULOS_PIEL("1420", "Fabricación de artículos de piel."),
    FABRICACION_ARTICULOS_PUNTO("1430", "Fabricación de artículos de punto y ganchillo."),
    CURTIDO_CUEROS("1511", "Curtido y recurtido de cueros; recurtido y teñido de pieles."),
    FABRICACION_ARTICULOS_CUERO("1512", "Fabricación de artículos de viaje, bolsos de mano y artículos similares elaborados en cuero, y fabricación de artículos de talabartería y guarnicionería."),
    ASERRADO_MADERA("1610", "Aserrado, acepillado e impregnación de la madera."),
    FABRICACION_HOJAS_MADERA("1620", "Fabricación de hojas de madera para enchapado; fabricación de tableros contrachapados, tableros laminados, tableros de partículas y otros tableros y paneles."),
    FABRICACION_PARTES_MADERA("1630", "Fabricación de partes y piezas de madera, de carpintería y ebanistería para la construcción."),
    FABRICACION_RECIPIENTES_MADERA("1640", "Fabricación de recipientes de madera."),
    FABRICACION_OTROS_PRODUCTOS_MADERA("1690", "Fabricación de otros productos de madera; fabricación de artículos de corcho, cestería y espartería."),
    FABRICACION_PULPAS("1701", "Fabricación de pulpas (pastas) celulósicas; papel y cartón."),
    FABRICACION_PAPEL_CARTON("1702", "Fabricación de papel y cartón ondulado (corrugado); fabricación de envases, empaques y de embalajes de papel y cartón."),
    FABRICACION_OTROS_ARTICULOS_PAPEL("1709", "Fabricación de otros artículos de papel y cartón."),
    ACTIVIDADES_IMPRESION("1811", "Actividades de impresión."),
    SERVICIOS_IMPRESION("1812", "Actividades de servicios relacionados con la impresión."),
    PRODUCCION_COPIAS("1820", "Producción de copias a partir de grabaciones originales."),
    FABRICACION_HORNOS_COQUE("1910", "Fabricación de productos de hornos de coque."),
    FABRICACION_PRODUCTOS_REFINACION("1921", "Fabricación de productos de la refinación del petróleo."),
    ACTIVIDAD_MEZCLA_COMBUSTIBLES("1922", "Actividad de mezcla de combustibles."),
    FABRICACION_SUSTANCIAS_QUIMICAS("2011", "Fabricación de sustancias y productos químicos básicos."),
    FABRICACION_ABONOS("2012", "Fabricación de abonos y compuestos inorgánicos nitrogenados."),
    FABRICACION_PLASTICOS("2013", "Fabricación de plásticos en formas primarias."),
    FABRICACION_CAUCHO_SINTETICO("2014", "Fabricación de caucho sintético en formas primarias."),
    FABRICACION_PLAGUICIDAS("2021", "Fabricación de plaguicidas y otros productos químicos de uso agropecuario."),
    FABRICACION_PINTURAS("2022", "Fabricación de pinturas, barnices y revestimientos similares, tintas para impresión y masillas."),
    FABRICACION_JABONES_DETERGENTES("2023", "Fabricación de jabones y detergentes, preparados para limpiar y pulir; perfumes y preparados de tocador."),
    FABRICACION_OTROS_PRODUCTOS_QUIMICOS("2029", "Fabricación de otros productos químicos n.c.p."),
    FABRICACION_FIBRAS_SINTETICAS("2030", "Fabricación de fibras sintéticas y artificiales."),
    FABRICACION_PRODUCTOS_FARMACEUTICOS("2100", "Fabricación de productos farmacéuticos, sustancias químicas medicinales y productos botánicos de uso farmacéutico."),
    FABRICACION_NEUMATICOS("2211", "Fabricación de neumáticos y cámaras de caucho; reconstrucción y recauchutado de neumáticos."),
    FABRICACION_PLACAS_LAMINAS("2221", "Fabricación de placas, láminas, tubos y perfiles de plástico."),
    FABRICACION_ENVASES_PLASTICO("2222", "Fabricación de envases y empaques de plástico."),
    FABRICACION_PRODUCTOS_PLASTICO("2223", "Fabricación de productos de plástico n.c.p."),
    FABRICACION_VIDRIO("2310", "Fabricación de vidrio y productos de vidrio."),
    FABRICACION_PRODUCTOS_MINERALES("2391", "Fabricación de productos abrasivos y productos minerales no metálicos n.c.p."),
    FABRICACION_OTROS_MINERALES("2399", "Fabricación de otros productos minerales no metálicos n.c.p."),
    METALURGIA_HIERRO("2410", "Metalurgia del hierro y fabricación de productos de hierro y acero."),
    FABRICACION_FERROALEACIONES("2420", "Fabricación de productos de ferroaleaciones."),
    FABRICACION_ESTRUCTURAS_METALICAS("2511", "Fabricación de estructuras metálicas y sus componentes."),
    FABRICACION_TANQUES_METAL("2512", "Fabricación de tanques, depósitos y recipientes de metal."),
    FABRICACION_CALDERAS("2521", "Fabricación de calderas y radiadores para calefacción central."),
    FABRICACION_OTROS_PRODUCTOS_METALICOS_CONSTRUCCION("2529", "Fabricación de otros productos metálicos para uso en la construcción."),
    FABRICACION_GENERADORES_VAPOR("2531", "Fabricación de generadores de vapor (excepto calderas de agua caliente para calefacción central)."),
    FABRICACION_OTROS_PRODUCTOS_METALICOS_INDUSTRIA("2539", "Fabricación de otros productos de metal para uso en la industria."),
    FORJA_METAL("2591", "Forja, prensado, estampado y laminado de metal; pulvimetalurgia."),
    TRATAMIENTO_REVETIMIENTO_METALES("2592", "Tratamiento y revestimiento de metales; maquinado."),
    FABRICACION_ARTICULOS_ALAMBRE("2593", "Fabricación de productos de alambre, cadenas y resortes."),
    FABRICACION_COMPONENTES_ELECTRONICOS("2610", "Fabricación de componentes y tableros electrónicos."),
    FABRICACION_EQUIPOS_COMUNICACION("2620", "Fabricación de equipos de cómputo y de comunicación, y de equipos periféricos."),
    FABRICACION_APARATOS_RADIO_TV("2630", "Fabricación de aparatos de radio, televisión y comunicación."),
    FABRICACION_APARATOS_GRABACION("2640", "Fabricación de aparatos de grabación y reproducción de sonido."),
    FABRICACION_APARATOS_MEDICION("2651", "Fabricación de aparatos y equipos de medición, prueba, navegación y control."),
    FABRICACION_RELOJES("2652", "Fabricación de relojes."),
    FABRICACION_SOPORTES_MAGNETICOS("2660", "Fabricación de soportes magnéticos y ópticos."),
    FABRICACION_INSTRUMENTOS_OPTICOS("2670", "Fabricación de instrumentos y aparatos de óptica."),
    FABRICACION_MOTORES_GENERADORES("2710", "Fabricación de motores, generadores y transformadores eléctricos."),
    FABRICACION_APARATOS_DISTRIBUCION("2720", "Fabricación de aparatos de distribución y control de la energía eléctrica."),
    FABRICACION_HILOS_CABLES("2731", "Fabricación de hilos y cables eléctricos aislados."),
    FABRICACION_DISPOSITIVOS_CABLEADO("2732", "Fabricación de dispositivos de cableado."),
    FABRICACION_ACUMULADORES_PILAS("2740", "Fabricación de acumuladores, pilas y baterías."),
    FABRICACION_LAMPARAS_TUBOS("2750", "Fabricación de lámparas y tubos eléctricos."),
    FABRICACION_OTROS_EQUIPOS_ELECTRICOS("2790", "Fabricación de otros tipos de equipo eléctrico n.c.p."),
    FABRICACION_MOTORES_TURBINAS("2811", "Fabricación de motores y turbinas, excepto motores de avión y vehículos de motor."),
    FABRICACION_EQUIPO_TRANSMISION_POTENCIA("2812", "Fabricación de equipo de transmisión de potencia y equipo de distribución eléctrica."),
    FABRICACION_MAQUINARIA_ELEVACION("2813", "Fabricación de maquinaria y equipo de elevación y manipulación."),
    FABRICACION_MAQUINARIA_REFRIGERACION("2814", "Fabricación de maquinaria y equipo de refrigeración y ventilación para usos industriales y comerciales."),
    FABRICACION_MAQUINARIA_AGRICULTURA("2815", "Fabricación de equipo de uso en la agricultura y la silvicultura (excepto máquinas y equipo para la agricultura y silvicultura)."),
    FABRICACION_MAQUINARIA_METALURGICA("2816", "Fabricación de máquinas y equipo para la industria metalúrgica."),
    FABRICACION_MAQUINARIA_ALIMENTOS("2817", "Fabricación de maquinaria y equipo para la industria de la alimentación, bebidas y tabaco."),
    FABRICACION_MAQUINARIA_TEXTIL("2818", "Fabricación de maquinaria y equipo para la industria textil, de prendas de vestir y cueros."),
    FABRICACION_OTRAS_MAQUINAS_EQUIPO("2819", "Fabricación de otras máquinas y equipo de uso general n.c.p."),
    FABRICACION_MAQUINARIA_OFICINA("2821", "Fabricación de maquinaria y equipo de oficina (excepto computadoras y equipo periférico)."),
    FABRICACION_MAQUINARIA_ESPECIAL("2822", "Fabricación de maquinaria y equipo de uso especial n.c.p."),
    FABRICACION_MAQUINARIA_HERRAMIENTA("2830", "Fabricación de máquinas herramienta."),
    FABRICACION_MAQUINARIA_MINERIA_CONSTRUCCION("2841", "Fabricación de maquinaria y equipo para la minería, la construcción y la ingeniería civil."),
    FABRICACION_OTRA_MAQUINARIA_ESPECIAL("2849", "Fabricación de otra maquinaria y equipo de uso especial n.c.p."),
    FABRICACION_VEHICULOS_AUTOMOTORES("2910", "Fabricación de vehículos automotores."),
    FABRICACION_CARROCERIAS("2920", "Fabricación de carrocerías para vehículos automotores; fabricación de remolques y semirremolques."),
    FABRICACION_PARTES_VEHICULOS("2930", "Fabricación de partes y accesorios para vehículos automotores."),
     CONSTRUCCION_BARCOS("3011", "Construcción de barcos y estructuras flotantes."),
    CONSTRUCCION_EMBARCACIONES_RECREO("3012", "Construcción de embarcaciones de recreo y deportivas."),
    FABRICACION_LOCOMOTORAS("3020", "Fabricación de locomotoras y material rodante para ferrocarriles."),
    FABRICACION_AERONAVES("3030", "Fabricación de aeronaves y naves espaciales."),
    FABRICACION_VEHICULOS_MILITARES("3040", "Fabricación de vehículos militares de combate."),
    FABRICACION_MOTOCICLETAS("3091", "Fabricación de motocicletas"),
    FABRICACION_BICICLETAS_SILLAS_RUEDAS("3092", "Fabricación de bicicletas y de sillas de ruedas para personas con discapacidad."),
    FABRICACION_OTROS_EQUIPOS_TRANSPORTE("3099", "Fabricación de otros tipos de equipo de transporte n.c.p."),
    FABRICACION_MUEBLES("3110", "Fabricación de muebles."),
    FABRICACION_COLCHONES_SOMIERES("3120", "Fabricación de colchones y somieres."),
    FABRICACION_JOYAS_BISUTERIA("3210", "Fabricación de joyas, bisutería y artículos conexos."),
    FABRICACION_INSTRUMENTOS_MUSICALES("3220", "Fabricación de instrumentos musicales."),
    FABRICACION_ARTICULOS_DEPORTE("3230", "Fabricación de artículos y equipo para la práctica del deporte."),
    FABRICACION_JUEGOS_JUGUETES("3240", "Fabricación de juegos, juguetes y rompecabezas."),
    FABRICACION_INSTRUMENTOS_MEDICOS("3250", "Fabricación de instrumentos, aparatos y materiales médicos y odontológicos (incluido mobiliario)."),
    OTRAS_INDUSTRIAS_MANUFACTURERAS("3290", "Otras industrias manufactureras n.c.p."),
    MANTENIMIENTO_REPARACION_METAL("3311", "Mantenimiento y reparación especializado de productos elaborados en metal."),
    MANTENIMIENTO_REPARACION_MAQUINARIA("3312", "Mantenimiento y reparación especializado de maquinaria y equipo."),
    MANTENIMIENTO_REPARACION_ELECTRONICO("3313", "Mantenimiento y reparación especializado de equipo electrónico y óptico."),
    MANTENIMIENTO_REPARACION_EQUIPO_ELECTRICO("3314", "Mantenimiento y reparación especializado de equipo eléctrico."),
    MANTENIMIENTO_REPARACION_EQUIPO_TRANSPORTE("3315", "Mantenimiento y reparación especializado de equipo de transporte, excepto los vehículos automotores, motocicletas y bicicletas."),
    MANTENIMIENTO_REPARACION_OTROS_EQUIPOS("3319", "Mantenimiento y reparación de otros tipos de equipos y sus componentes n.c.p."),
    INSTALACION_ESPECIALIZADA_MAQUINARIA("3320", "Instalación especializada de maquinaria y equipo industrial."),
    GENERACION_ENERGIA_ELECTRICA("3511", "Generación de energía eléctrica."),
    TRANSMISION_ENERGIA_ELECTRICA("3512", "Transmisión de energía eléctrica."),
    DISTRIBUCION_ENERGIA_ELECTRICA("3513", "Distribución de energía eléctrica."),
    COMERCIALIZACION_ENERGIA_ELECTRICA("3514", "Comercialización de energía eléctrica."),
    PRODUCCION_GAS("3520", "Producción de gas; distribución de combustibles gaseosos por tuberías."),
    SUMINISTRO_VAPOR_AIRE_ACONDICIONADO("3530", "Suministro de vapor y aire acondicionado."),
    CAPTACION_TRATAMIENTO_AGUA("3600", "Captación, tratamiento y distribución de agua."),
    EVACUACION_TRATAMIENTO_AGUAS_RESIDUALES("3700", "Evacuación y tratamiento de aguas residuales."),
    RECOLECCION_DESECHOS_NO_PELIGROSOS("3811", "Recolección de desechos no peligrosos."),
    RECOLECCION_DESECHOS_PELIGROSOS("3812", "Recolección de desechos peligrosos."),
    TRATAMIENTO_DESECHOS_NO_PELIGROSOS("3821", "Tratamiento y disposición de desechos no peligrosos."),
    TRATAMIENTO_DESECHOS_PELIGROSOS("3822", "Tratamiento y disposición de desechos peligrosos."),
    RECUPERACION_MATERIALES("3830", "Recuperación de materiales."),
    ACTIVIDADES_SANEAMIENTO_AMBIENTAL("3900", "Actividades de saneamiento ambiental y otros servicios de gestión de desechos."),
    CONSTRUCCION_EDIFICIOS_RESIDENCIALES("4111", "Construcción de edificios residenciales."),
    CONSTRUCCION_EDIFICIOS_NO_RESIDENCIALES("4112", "Construcción de edificios no residenciales."),
    CONSTRUCCION_CARRETERAS("4210", "Construcción de carreteras y vías de ferrocarril."),
    CONSTRUCCION_PROYECTOS_SERVICIO_PUBLICO("4220", "Construcción de proyectos de servicio público."),
    CONSTRUCCION_OTRAS_OBRAS_CIVILES("4290", "Construcción de otras obras de ingeniería civil."),
    DEMOLICION("4311", "Demolición."),
    PREPARACION_TERRENO("4312", "Preparación del terreno."),
    INSTALACIONES_ELECTRICAS("4321", "Instalaciones eléctricas."),
    INSTALACIONES_FONTANERIA_CALEFACCION("4322", "Instalaciones de fontanería, calefacción y aire acondicionado."),
    OTRAS_INSTALACIONES_ESPECIALIZADAS("4329", "Otras instalaciones especializadas."),
    TERMINACION_ACABADO_EDIFICIOS("4330", "Terminación y acabado de edificios y obras de ingeniería civil."),
    OTRAS_ACTIVIDADES_ESPECIALIZADAS_CONSTRUCCION("4390", "Otras actividades especializadas para la construcción de edificios y obras de ingeniería civil."),
    COMERCIO_VEHICULOS_AUTOMOTORES_NUEVOS("4511", "Comercio de vehículos automotores nuevos."),
    COMERCIO_VEHICULOS_AUTOMOTORES_USADOS("4512", "Comercio de vehículos automotores usados."),
    MANTENIMIENTO_REPARACION_VEHICULOS_AUTOMOTORES("4520", "Mantenimiento y reparación de vehículos automotores."),
    COMERCIO_PARTES_PIEZAS_ACCESORIOS("4530", "Comercio de partes, piezas (autopartes) y accesorios (lujos) para vehículos automotores."),
    COMERCIO_MOTOCICLETAS("4541", "Comercio de motocicletas y de sus partes, piezas y accesorios."),
    MANTENIMIENTO_REPARACION_MOTOCICLETAS("4542", "Mantenimiento y reparación de motocicletas y de sus partes y piezas."),
    COMERCIO_MAYOR_RETRIBUCION("4610", "Comercio al por mayor a cambio de una retribución o por contrata."),
    COMERCIO_MAYOR_MATERIAS_PRIMAS_AGROPECUARIAS("4620", "Comercio al por mayor de materias primas agropecuarias; animales vivos."),
    COMERCIO_MAYOR_PRODUCTOS_ALIMENTICIOS("4631", "Comercio al por mayor de productos alimenticios."),
    COMERCIO_MAYOR_BEBIDAS_TABACO("4632", "Comercio al por mayor de bebidas y tabaco."),
    COMERCIO_MAYOR_TEXTILES_CONFECCIONADOS("4641", "Comercio al por mayor de productos textiles, productos confeccionados para uso doméstico."),
    COMERCIO_MAYOR_PRENDAS_VESTIR("4642", "Comercio al por mayor de prendas de vestir."),
    COMERCIO_MAYOR_CALZADO("4643", "Comercio al por mayor de calzado."),
    COMERCIO_MAYOR_APARATOS_EQUIPO_DOMESTICO("4644", "Comercio al por mayor de aparatos y equipo de uso doméstico."),
    COMERCIO_MAYOR_PRODUCTOS_FARMACEUTICOS("4645", "Comercio al por mayor de productos farmacéuticos, medicinales, cosméticos y de tocador."),
    COMERCIO_MAYOR_UTENSILIOS_DOMESTICOS("4649", "Comercio al por mayor de otros utensilios domésticos n.c.p."),
    COMERCIO_MAYOR_COMPUTADORES_EQUIPO_PERIFERICO("4651", "Comercio al por mayor de computadores, equipo periférico y programas de informática."),
    COMERCIO_MAYOR_EQUIPO_ELECTRONICO("4652", "Comercio al por mayor de equipo, partes y piezas electrónicos y de telecomunicaciones."),
    COMERCIO_MAYOR_MAQUINARIA_EQUIPO_AGROPECUARIO("4653", "Comercio al por mayor de maquinaria y equipo agropecuarios."),
    COMERCIO_MAYOR_OTROS_TIPOS_MAQUINARIA_EQUIPO("4659", "Comercio al por mayor de otros tipos de maquinaria y equipo n.c.p."),
    COMERCIO_MAYOR_COMBUSTIBLES("4661", "Comercio al por mayor de combustibles sólidos, líquidos, gaseosos y productos conexos."),
    COMERCIO_MAYOR_METALES_PRODUCTOS_METALIFEROS("4662", "Comercio al por mayor de metales y productos metalíferos."),
    COMERCIO_MAYOR_MATERIALES_CONSTRUCCION("4663", "Comercio al por mayor de materiales de construcción, artículos de ferretería, pinturas, productos de vidrio, equipo y materiales de fontanería y calefacción."),
    COMERCIO_MAYOR_PRODUCTOS_QUIMICOS("4664", "Comercio al por mayor de productos químicos básicos, cauchos y plásticos en formas primarias y productos químicos de uso agropecuario."),
    COMERCIO_MAYOR_DESECHOS_CHATARRA("4665", "Comercio al por mayor de desperdicios, desechos y chatarra."),
    COMERCIO_MAYOR_OTROS_PRODUCTOS("4669", "Comercio al por mayor de otros productos n.c.p."),
    COMERCIO_MAYOR_NO_ESPECIALIZADO("4690", "Comercio al por mayor no especializado."),
    COMERCIO_MENOR_ALIMENTOS_BEBIDAS_TABACO("4711", "Comercio al por menor en establecimientos no especializados con surtido compuesto principalmente por alimentos, bebidas o tabaco."),
    COMERCIO_MENOR_OTROS_PRODUCTOS("4719", "Comercio al por menor en establecimientos no especializados, con surtido compuesto principalmente por productos diferentes de alimentos (víveres en general), bebidas y tabaco."),
    COMERCIO_MENOR_PRODUCTOS_AGRICOLAS("4721", "Comercio al por menor de productos agrícolas para el consumo en establecimientos especializados."),
    COMERCIO_MENOR_LECHE_PRODUCTOS_LACTEOS_HUEVOS("4722", "Comercio al por menor de leche, productos lácteos y huevos, en establecimientos especializados."),
    COMERCIO_MENOR_CARNES_PESCADOS_MARISCOS("4723", "Comercio al por menor de carnes (incluye aves de corral), productos cárnicos, pescados y productos de mar, en establecimientos especializados."),
    COMERCIO_MENOR_BEBIDAS_TABACO("4724", "Comercio al por menor de bebidas y productos del tabaco, en establecimientos especializados."),
    COMERCIO_MENOR_OTROS_ALIMENTOS("4729", "Comercio al por menor de otros productos alimenticios n.c.p., en establecimientos especializados."),
    COMERCIO_MENOR_COMBUSTIBLE_AUTOMOTORES("4731", "Comercio al por menor de combustible para automotores."),
    COMERCIO_MENOR_LUBRICANTES("4732", "Comercio al por menor de lubricantes (aceites, grasas), aditivos y productos de limpieza para vehículos automotores."),
    COMERCIO_MENOR_COMPUTADORES_EQUIPO_PERIFERICO("4741", "Comercio al por menor de computadores, equipos periféricos, programas de informática y equipos de telecomunicaciones en establecimientos especializados."),
    COMERCIO_MENOR_EQUIPO_SONIDO_VIDEO("4742", "Comercio al por menor de equipos y aparatos de sonido y de video, en establecimientos especializados."),
    COMERCIO_MENOR_PRODUCTOS_TEXTILES("4751", "Comercio al por menor de productos textiles en establecimientos especializados."),
    COMERCIO_MENOR_ARTICULOS_FERRETERIA_PINTURAS("4752", "Comercio al por menor de artículos de ferretería, pinturas y productos de vidrio en establecimientos especializados."),
    COMERCIO_MENOR_TAPECES_ALFOMBRAS("4753", "Comercio al por menor de tapices, alfombras y cubrimientos para paredes y pisos en establecimientos especializados."),
    COMERCIO_MENOR_ELECTRODOMESTICOS("4754", "Comercio al por menor de electrodomésticos y gasodomésticos de uso doméstico, muebles y equipos de iluminación."),
    COMERCIO_MENOR_ARTICULOS_UTENSILIOS_DOMESTICOS("4755", "Comercio al por menor de artículos y utensilios de uso doméstico."),
    COMERCIO_MENOR_LIBROS_ARTICULOS_PAPELERIA("4761", "Comercio al por menor de libros, periódicos, materiales y artículos de papelería y escritorio, en establecimientos especializados."),
    COMERCIO_MENOR_ARTICULOS_DEPORTIVOS("4762", "Comercio al por menor de artículos deportivos, en establecimientos especializados."),
    COMERCIO_MENOR_OTROS_ARTICULOS_CULTURALES_ENTRETENIMIENTO("4769", "Comercio al por menor de otros artículos culturales y de entretenimiento n.c.p. en establecimientos especializados."),
    COMERCIO_MENOR_PRENDAS_VESTIR_ACCESORIOS("4771", "Comercio al por menor de prendas de vestir y sus accesorios (incluye artículos de piel) en establecimientos especializados."),
    COMERCIO_MENOR_CALZADO_ARTICULOS_CUERO("4772", "Comercio al por menor de todo tipo de calzado y artículos de cuero y sucedáneos del cuero en establecimientos especializados."),
    COMERCIO_MENOR_PRODUCTOS_FARMACEUTICOS("4773", "Comercio al por menor de productos farmacéuticos y medicinales, cosméticos y artículos de tocador en establecimientos especializados."),
    COMERCIO_MENOR_OTROS_PRODUCTOS_NUEVOS("4774", "Comercio al por menor de otros productos nuevos en establecimientos especializados."),
    COMERCIO_MENOR_ARTICULOS_SEGUNDA_MANO("4775", "Comercio al por menor de artículos de segunda mano."),
    COMERCIO_MENOR_ALIMENTOS_BEBIDAS_TABACO_PUESTOS("4781", "Comercio al por menor de alimentos, bebidas y tabaco, en puestos de venta móviles."),
    COMERCIO_MENOR_TEXTILES_VESTIR_CALZADO_PUESTOS("4782", "Comercio al por menor de productos textiles, prendas de vestir y calzado, en puestos de venta móviles."),
    COMERCIO_MENOR_OTROS_PRODUCTOS_PUESTOS("4789", "Comercio al por menor de otros productos en puestos de venta móviles."),
    COMERCIO_MENOR_INTERNET("4791", "Comercio al por menor realizado a través de internet."),
    COMERCIO_MENOR_CASAS_VENTA_CORREO("4792", "Comercio al por menor realizado a través de casas de venta o por correo."),
    OTROS_COMERCIOS_MENOR("4799", "Otros tipos de comercio al por menor no realizado en establecimientos, puestos de venta o mercados."),
    TRANSPORTE_FERREO_PASAJEROS("4911", "Transporte férreo de pasajeros."),
    TRANSPORTE_FERREO_CARGA("4912", "Transporte férreo de carga."),
    TRANSPORTE_PASAJEROS("4921", "Transporte de pasajeros."),
    TRANSPORTE_MIXTO("4922", "Transporte mixto."),
    TRANSPORTE_CARGA_CARRETERA("4923", "Transporte de carga por carretera."),
    TRANSPORTE_TUBERIAS("4930", "Transporte por tuberías."),
    TRANSPORTE_DE_PASAJEROS_MARITIMO_Y_DE_CABOTAJE("5011", "Transporte de pasajeros marítimo y de cabotaje."),
    TRANSPORTE_DE_CARGA_MARITIMO_Y_DE_CABOTAJE("5012", "Transporte de carga marítimo y de cabotaje."),
    TRANSPORTE_FLUVIAL_DE_PASAJEROS("5021", "Transporte fluvial de pasajeros."),
    TRANSPORTE_FLUVIAL_DE_CARGA("5022", "Transporte fluvial de carga."),
    TRANSPORTE_AEREO_NACIONAL_DE_PASAJEROS("5111", "Transporte aéreo nacional de pasajeros."),
    TRANSPORTE_AEREO_INTERNACIONAL_DE_PASAJEROS("5112", "Transporte aéreo internacional de pasajeros."),
    TRANSPORTE_AEREO_NACIONAL_DE_CARGA("5121", "Transporte aéreo nacional de carga."),
    TRANSPORTE_AEREO_INTERNACIONAL_DE_CARGA("5122", "Transporte aéreo internacional de carga."),
    ALMACENAMIENTO_Y_DEPOSITO("5210", "Almacenamiento y depósito."),
    ACTIVIDADES_DE_ESTACIONES_VIAS_Y_SERVICIOS_COMPLEMENTARIOS_PARA_EL_TRANSPORTE_TERRESTRE("5221", "Actividades de estaciones, vías y servicios complementarios para el transporte terrestre."),
    ACTIVIDADES_DE_PUERTOS_Y_SERVICIOS_COMPLEMENTARIOS_PARA_EL_TRANSPORTE_ACUATICO("5222", "Actividades de puertos y servicios complementarios para el transporte acuático."),
    ACTIVIDADES_DE_AEROPUERTOS_SERVICIOS_DE_NAVEGACION_AEREA_Y_DEMAS_ACTIVIDADES_CONEXAS_AL_TRANSPORTE_AEREO("5223", "Actividades de aeropuertos, servicios de navegación aérea y demás actividades conexas al transporte aéreo."),
    MANIPULACION_DE_CARGA("5224", "Manipulación de carga."),
    OTRAS_ACTIVIDADES_COMPLEMENTARIAS_AL_TRANSPORTE("5229", "Otras actividades complementarias al transporte."),
    ACTIVIDADES_POSTALES_NACIONALES("5310", "Actividades postales nacionales."),
    ACTIVIDADES_DE_MENSAJERIA("5320", "Actividades de mensajería."),
    ALOJAMIENTO_EN_HOTELES("5511", "Alojamiento en hoteles."),
    ALOJAMIENTO_EN_APARTAHOTELES("5512", "Alojamiento en apartahoteles."),
    ALOJAMIENTO_EN_CENTROS_VACACIONALES("5513", "Alojamiento en centros vacacionales."),
    ALOJAMIENTO_RURAL("5514", "Alojamiento rural."),
    OTROS_TIPOS_DE_ALOJAMIENTOS_PARA_VISITANTES("5519", "Otros tipos de alojamientos para visitantes."),
    ACTIVIDADES_DE_ZONAS_DE_CAMPING_Y_PARQUES_PARA_VEHICULOS_RECREACIONALES("5520", "Actividades de zonas de camping y parques para vehículos recreacionales."),
    SERVICIO_POR_HORAS("5530", "Servicio por horas."),
    OTROS_TIPOS_DE_ALOJAMIENTO_NCP("5590", "Otros tipos de alojamiento n.c.p."),
    EXPENDIO_A_LA_MESA_DE_COMIDAS_PREPARADAS("5611", "Expendio a la mesa de comidas preparadas."),
    EXPENDIO_POR_AUTOSERVICIO_DE_COMIDAS_PREPARADAS("5612", "Expendio por autoservicio de comidas preparadas."),
    EXPENDIO_DE_COMIDAS_PREPARADAS_EN_CAFETERIAS("5613", "Expendio de comidas preparadas en cafeterías."),
    OTROS_TIPOS_DE_EXPENDIO_DE_COMIDAS_PREPARADAS_NCP("5619", "Otros tipos de expendio de comidas preparadas n.c.p."),
    CATERING_PARA_EVENTOS("5621", "Catering para eventos."),
    ACTIVIDADES_DE_OTROS_SERVICIOS_DE_COMIDAS("5629", "Actividades de otros servicios de comidas."),
    EXPENDIO_DE_BEBIDAS_ALCOHOLICAS_PARA_EL_CONSUMO_DENTRO_DEL_ESTABLECIMIENTO("5630", "Expendio de bebidas alcohólicas para el consumo dentro del establecimiento."),
    EDICION_DE_LIBROS("5811", "Edición de libros."),
    EDICION_DE_DIRECTORIOS_Y_LISTAS_DE_CORREO("5812", "Edición de directorios y listas de correo."),
    EDICION_DE_PERIODICOS_REVISTAS_Y_OTRAS_PUBLICACIONES_PERIODICAS("5813", "Edición de periódicos, revistas y otras publicaciones periódicas."),
    OTROS_TRABAJOS_DE_EDICION("5819", "Otros trabajos de edición."),
    EDICION_DE_PROGRAMAS_DE_INFORMATICA_SOFTWARE("5820", "Edición de programas de informática (software)."),
    ACTIVIDADES_DE_PRODUCCION_DE_PELICULAS_CINEMATOGRAFICAS_VIDEOS_PROGRAMAS_ANUNCIOS_Y_COMERCIALES_DE_TELEVISION("5911", "Actividades de producción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión."),
    ACTIVIDADES_DE_POSPRODUCCION_DE_PELICULAS_CINEMATOGRAFICAS_VIDEOS_PROGRAMAS_ANUNCIOS_Y_COMERCIALES_DE_TELEVISION("5912", "Actividades de posproducción de películas cinematográficas, videos, programas, anuncios y comerciales de televisión."),
    ACTIVIDADES_DE_DISTRIBUCION_DE_PELICULAS_CINEMATOGRAFICAS_VIDEOS_PROGRAMAS_ANUNCIOS_Y_COMERCIALES_DE_TELEVISION("5913", "Actividades de distribución de películas cinematográficas, videos, programas, anuncios y comerciales de televisión."),
    ACTIVIDADES_DE_EXHIBICION_DE_PELICULAS_CINEMATOGRAFICAS_Y_VIDEOS("5914", "Actividades de exhibición de películas cinematográficas y videos."),
    ACTIVIDADES_DE_GRABACION_DE_SONIDO_Y_EDICION_DE_MUSICA("5920", "Actividades de grabación de sonido y edición de música."),
    ACTIVIDADES_DE_PROGRAMACION_Y_TRANSMISION_EN_EL_SERVICIO_DE_RADIODIFUSION_SONORA("6010", "Actividades de programación y transmisión en el servicio de radiodifusión sonora."),
    ACTIVIDADES_DE_PROGRAMACION_Y_TRANSMISION_DE_TELEVISION("6020", "Actividades de programación y transmisión de televisión."),
    ACTIVIDADES_DE_TELECOMUNICACIONES_ALAMBRICAS("6110", "Actividades de telecomunicaciones alámbricas."),
    ACTIVIDADES_DE_TELECOMUNICACIONES_INALAMBRICAS("6120", "Actividades de telecomunicaciones inalámbricas."),
    ACTIVIDADES_DE_TELECOMUNICACION_SATELITAL("6130", "Actividades de telecomunicación satelital."),
    OTRAS_ACTIVIDADES_DE_TELECOMUNICACIONES("6190", "Otras actividades de telecomunicaciones."),
    ACTIVIDADES_DE_DESARROLLO_DE_SISTEMAS_INFORMATICOS("6201", "Actividades de desarrollo de sistemas informáticos (planificación, análisis, diseño, programación, pruebas)."),
    ACTIVIDADES_DE_CONSULTORIA_INFORMATICA_Y_ACTIVIDADES_DE_ADMINISTRACION_DE_INSTALACIONES_INFORMATICAS("6202", "Actividades de consultoría informática y actividades de administración de instalaciones informáticas."),
    OTRAS_ACTIVIDADES_DE_TECNOLOGIAS_DE_INFORMACION_Y_ACTIVIDADES_DE_SERVICIOS_INFORMATICOS("6209", "Otras actividades de tecnologías de información y actividades de servicios informáticos."),
    PROCESAMIENTO_DE_DATOS_ALOJAMIENTO_HOSTING_Y_ACTIVIDADES_RELACIONADAS("6311", "Procesamiento de datos, alojamiento (hosting) y actividades relacionadas."),
    PORTALES_WEB("6312", "Portales web."),
    ACTIVIDADES_DE_AGENCIAS_DE_NOTICIAS("6391", "Actividades de agencias de noticias."),
    OTRAS_ACTIVIDADES_DE_SERVICIO_DE_INFORMACION_NCP("6399", "Otras actividades de servicio de información n.c.p."),
    BANCO_CENTRAL("6411", "Banco Central."),
    BANCOS_COMERCIALES("6412", "Bancos comerciales."),
    ACTIVIDADES_DE_LAS_CORPORACIONES_FINANCIERAS("6421", "Actividades de las corporaciones financieras."),
    ACTIVIDADES_DE_LAS_COMPANIAS_DE_FINANCIAMIENTO("6422", "Actividades de las compañías de financiamiento."),
    BANCA_DE_SEGUNDO_PISO("6423", "Banca de segundo piso."),
    ACTIVIDADES_DE_LAS_COOPERATIVAS_FINANCIERAS("6424", "Actividades de las cooperativas financieras."),
    FIDEICOMISOS_FONDOS_Y_ENTIDADES_FINANCIERAS_SIMILARES("6431", "Fideicomisos, fondos y entidades financieras similares."),
    FONDOS_DE_CESANTIAS("6432", "Fondos de cesantías."),
    LEASING_FINANCIERO_ARRENDAMIENTO_FINANCIERO("6491", "Leasing financiero (arrendamiento financiero)."),
    ACTIVIDADES_FINANCIERAS_DE_FONDOS_DE_EMPLEADOS_Y_OTRAS_FORMAS_ASOCIATIVAS_DEL_SECTOR_SOLIDARIO("6492", "Actividades financieras de fondos de empleados y otras formas asociativas del sector solidario."),
    ACTIVIDADES_DE_COMPRA_DE_CARTERA_O_FACTORING("6493", "Actividades de compra de cartera o factoring."),
    OTRAS_ACTIVIDADES_DE_DISTRIBUCION_DE_FONDOS("6494", "Otras actividades de distribución de fondos."),
    INSTITUCIONES_ESPECIALES_OFICIALES("6495", "Instituciones especiales oficiales."),
    OTRAS_ACTIVIDADES_DE_SERVICIO_FINANCIERO_EXCEPTO_LAS_DE_SEGUROS_Y_PENSIONES_NCP("6499", "Otras actividades de servicio financiero, excepto las de seguros y pensiones n.c.p."),
    SEGUROS_GENERALES("6511", "Seguros generales."),
    SEGUROS_DE_VIDA("6512", "Seguros de vida."),
    REASEGUROS("6513", "Reaseguros."),
    CAPITALIZACION("6514", "Capitalización."),
    SERVICIOS_DE_SEGUROS_SOCIALES_DE_SALUD("6521", "Servicios de seguros sociales de salud."),
    SERVICIOS_DE_SEGUROS_SOCIALES_DE_RIESGOS_PROFESIONALES("6522", "Servicios de seguros sociales de riesgos profesionales."),
    REGIMEN_DE_PRIMA_MEDIA_CON_PRESTACION_DEFINIDA_RPM("6531", "Régimen de prima media con prestación definida (RPM)."),
    REGIMEN_DE_AHORRO_INDIVIDUAL_RAI("6532", "Régimen de ahorro individual (RAI)."),
    ADMINISTRACION_DE_MERCADOS_FINANCIEROS("6611", "Administración de mercados financieros."),
    CORRETAJE_DE_VALORES_Y_DE_CONTRATOS_DE_PRODUCTOS_BASICOS("6612", "Corretaje de valores y de contratos de productos básicos."),
    OTRAS_ACTIVIDADES_RELACIONADAS_CON_EL_MERCADO_DE_VALORES("6613", "Otras actividades relacionadas con el mercado de valores."),
    ACTIVIDADES_DE_LAS_CASAS_DE_CAMBIO("6614", "Actividades de las casas de cambio."),
    ACTIVIDADES_DE_LOS_PROFESIONALES_DE_COMPRA_Y_VENTA_DE_DIVISAS("6615", "Actividades de los profesionales de compra y venta de divisas."),
    OTRAS_ACTIVIDADES_AUXILIARES_DE_LAS_ACTIVIDADES_DE_SERVICIOS_FINANCIEROS_NCP("6619", "Otras actividades auxiliares de las actividades de servicios financieros n.c.p."),
    ACTIVIDADES_DE_AGENTES_Y_CORREDORES_DE_SEGUROS("6621", "Actividades de agentes y corredores de seguros."),
    EVALUACION_DE_RIESGOS_Y_DANOS_Y_OTRAS_ACTIVIDADES_DE_SERVICIOS_AUXILIARES("6629", "Evaluación de riesgos y daños, y otras actividades de servicios auxiliares."),
    ACTIVIDADES_DE_ADMINISTRACION_DE_FONDOS("6630", "Actividades de administración de fondos."),
    ACTIVIDADES_INMOBILIARIAS_REALIZADAS_CON_BIENES_PROPIOS_O_ARRENDADOS("6810", "Actividades inmobiliarias realizadas con bienes propios o arrendados."),
    ACTIVIDADES_INMOBILIARIAS_REALIZADAS_A_CAMBIO_DE_UNA_RETRIBUCION_O_POR_CONTRATA("6820", "Actividades inmobiliarias realizadas a cambio de una retribución o por contrata."),
    ACTIVIDADES_JURIDICAS("6910", "Actividades jurídicas."),
    ACTIVIDADES_DE_CONTABILIDAD_TENEDURIA_DE_LIBROS_AUDITORIA_FINANCIERA_Y_ASESORIA_TRIBUTARIA("6920", "Actividades de contabilidad, teneduría de libros, auditoría financiera y asesoría tributaria."),
    ACTIVIDADES_DE_ADMINISTRACION_EMPRESARIAL("7010", "Actividades de administración empresarial."),
    ACTIVIDADES_DE_CONSULTORIA_DE_GESTION("7020", "Actividades de consultoría de gestión."),
    ACTIVIDADES_DE_ARQUITECTURA_E_INGENIERIA_Y_OTRAS_ACTIVIDADES_CONEXAS_DE_CONSULTORIA_TECNICA("7110", "Actividades de arquitectura e ingeniería y otras actividades conexas de consultoría técnica."),
    ENSAYOS_Y_ANALISIS_TECNICOS("7120", "Ensayos y análisis técnicos."),
    INVESTIGACIONES_Y_DESARROLLO_EXPERIMENTAL_EN_EL_CAMPO_DE_LAS_CIENCIAS_NATURALES_Y_LA_INGENIERIA("7210", "Investigaciones y desarrollo experimental en el campo de las ciencias naturales y la ingeniería."),
    INVESTIGACIONES_Y_DESARROLLO_EXPERIMENTAL_EN_EL_CAMPO_DE_LAS_CIENCIAS_SOCIALES_Y_LAS_HUMANIDADES("7220", "Investigaciones y desarrollo experimental en el campo de las ciencias sociales y las humanidades."),
    PUBLICIDAD("7310", "Publicidad."),
    ESTUDIOS_DE_MERCADO_Y_REALIZACION_DE_ENCUESTAS_DE_OPINION_PUBLICA("7320", "Estudios de mercado y realización de encuestas de opinión pública."),
    ACTIVIDADES_ESPECIALIZADAS_DE_DISENO("7410", "Actividades especializadas de diseño."),
    ACTIVIDADES_DE_FOTOGRAFIA("7420", "Actividades de fotografía."),
    OTRAS_ACTIVIDADES_PROFESIONALES_CIENTIFICAS_Y_TECNICAS_NCP("7490", "Otras actividades profesionales, científicas y técnicas n.c.p."),
    ACTIVIDADES_VETERINARIAS("7500", "Actividades veterinarias."),
    ALQUILER_Y_ARRENDAMIENTO_DE_VEHICULOS_AUTOMOTORES("7710", "Alquiler y arrendamiento de vehículos automotores."),
    ALQUILER_Y_ARRENDAMIENTO_DE_EQUIPO_RECREATIVO_Y_DEPORTIVO("7721", "Alquiler y arrendamiento de equipo recreativo y deportivo."),
    ALQUILER_DE_VIDEOS_Y_DISCOS("7722", "Alquiler de videos y discos."),
    ALQUILER_Y_ARRENDAMIENTO_DE_OTROS_EFECTOS_PERSONALES_Y_ENSERES_DOMESTICOS_NCP("7729", "Alquiler y arrendamiento de otros efectos personales y enseres domésticos n.c.p."),
    ALQUILER_Y_ARRENDAMIENTO_DE_OTROS_TIPOS_DE_MAQUINARIA_EQUIPO_Y_BIENES_TANGIBLES_NCP("7730", "Alquiler y arrendamiento de otros tipos de maquinaria, equipo y bienes tangibles n.c.p."),
    ARRENDAMIENTO_DE_PROPIEDAD_INTELECTUAL_Y_PRODUCTOS_SIMILARES_EXCEPTO_OBRAS_PROTEGIDAS_POR_DERECHOS_DE_AUTOR("7740", "Arrendamiento de propiedad intelectual y productos similares, excepto obras protegidas por derechos de autor."),
    ACTIVIDADES_DE_AGENCIAS_DE_EMPLEO("7810", "Actividades de agencias de empleo."),
    ACTIVIDADES_DE_AGENCIAS_DE_EMPLEO_TEMPORAL("7820", "Actividades de agencias de empleo temporal."),
    OTRAS_ACTIVIDADES_DE_SUMINISTRO_DE_RECURSO_HUMANO("7830", "Otras actividades de suministro de recurso humano."),
    ACTIVIDADES_DE_LAS_AGENCIAS_DE_VIAJE("7911", "Actividades de las agencias de viaje."),
    ACTIVIDADES_DE_OPERADORES_TURISTICOS("7912", "Actividades de operadores turísticos."),
    OTROS_SERVICIOS_DE_RESERVA_Y_ACTIVIDADES_RELACIONADAS("7990", "Otros servicios de reserva y actividades relacionadas."),
    ACTIVIDADES_DE_SEGURIDAD_PRIVADA("8010", "Actividades de seguridad privada."),
    ACTIVIDADES_DE_SERVICIOS_DE_SISTEMAS_DE_SEGURIDAD("8020", "Actividades de servicios de sistemas de seguridad."),
    ACTIVIDADES_DE_DETECTIVES_E_INVESTIGADORES_PRIVADOS("8030", "Actividades de detectives e investigadores privados."),
    ACTIVIDADES_COMBINADAS_DE_APOYO_A_INSTALACIONES("8110", "Actividades combinadas de apoyo a instalaciones."),
    LIMPIEZA_GENERAL_INTERIOR_DE_EDIFICIOS("8121", "Limpieza general interior de edificios."),
    OTRAS_ACTIVIDADES_DE_LIMPIEZA_DE_EDIFICIOS_E_INSTALACIONES_INDUSTRIALES("8129", "Otras actividades de limpieza de edificios e instalaciones industriales."),
    ACTIVIDADES_DE_PAISAJISMO_Y_SERVICIOS_DE_MANTENIMIENTO_CONEXOS("8130", "Actividades de paisajismo y servicios de mantenimiento conexos."),
    ACTIVIDADES_COMBINADAS_DE_SERVICIOS_ADMINISTRATIVOS_DE_OFICINA("8211", "Actividades combinadas de servicios administrativos de oficina."),
    FOTOCOPIADO_PREPARACION_DE_DOCUMENTOS_Y_OTRAS_ACTIVIDADES_ESPECIALIZADAS_DE_APOYO_A_OFICINA("8219", "Fotocopiado, preparación de documentos y otras actividades especializadas de apoyo a oficina."),
    ACTIVIDADES_DE_CENTROS_DE_LLAMADAS_CALL_CENTER("8220", "Actividades de centros de llamadas (Call center)."),
    ORGANIZACION_DE_CONVENCIONES_Y_EVENTOS_COMERCIALES("8230", "Organización de convenciones y eventos comerciales."),
    ACTIVIDADES_DE_AGENCIAS_DE_COBRANZA_Y_OFICINAS_DE_CALIFICACION_CREDITICIA("8291", "Actividades de agencias de cobranza y oficinas de calificación crediticia."),
    ACTIVIDADES_DE_ENVASE_Y_EMPAQUE("8292", "Actividades de envase y empaque."),
    OTRAS_ACTIVIDADES_DE_SERVICIOS_EMPRESARIALES_NCP("8299", "Otras actividades de servicios empresariales n.c.p."),
    ADMINISTRACION_PUBLICA_Y_DEFENSA("8411", "Administración pública y defensa."),
    PLANES_DE_SEGURIDAD_SOCIAL_DE_AFINIDAD("8412", "Planes de seguridad social de afinidad."),
    SEGURIDAD_SOCIAL_OBLIGATORIA("8413", "Seguridad social obligatoria."),
    ACTIVIDADES_DE_REGULACION_Y_FACILITACION_DE_LA_ACTUACION_DE_ENTIDADES_EN_LOS_MERCADOS_FINANCIEROS("8414", "Actividades de regulación y facilitación de la actuación de entidades en los mercados financieros."),
    PRESTACION_DE_SERVICIOS_A_LAS_COMUNIDADES("8421", "Prestación de servicios a las comunidades."),
    ACTIVIDADES_DE_ASOCIACIONES_EMPRESARIALES_Y_DE_EMPLEADORES("8422", "Actividades de asociaciones empresariales y de empleadores."),
    ACTIVIDADES_DE_ASOCIACIONES_PROFESIONALES("8423", "Actividades de asociaciones profesionales."),
    ACTIVIDADES_DE_OTRAS_ASOCIACIONES_NCP("8429", "Actividades de otras asociaciones n.c.p."),
    EDUCACION_PREESCOLAR("8510", "Educación preescolar."),
    EDUCACION_PRIMARIA("8521", "Educación primaria."),
    EDUCACION_SECUNDARIA_DE_BASICA("8522", "Educación secundaria de básica."),
    EDUCACION_DE_JOVENES_Y_ADULTOS_DE_BASICA("8530", "Educación de jóvenes y adultos de básica."),
    EDUCACION_MEDIA_ACADEMICA("8541", "Educación media académica."),
    EDUCACION_MEDIA_TECNICA("8542", "Educación media técnica."),
    EDUCACION_MEDIA_VOCACIONAL("8543", "Educación media vocacional."),
    FORMACION_ACADEMICA_PROFESIONAL("8544", "Formación académica profesional."),
    EDUCACION_SUPERIOR("8551", "Educación superior."),
    POSTGRADOS("8552", "Postgrados."),
    OTRAS_ACTIVIDADES_DE_ENSENANZA("8560", "Otras actividades de enseñanza."),
    ACTIVIDADES_DE_BIBLIOTECAS_ARCHIVOS_MUSEOS_Y_OTRAS_ACTIVIDADES_CULTURALES("9101", "Actividades de bibliotecas, archivos, museos y otras actividades culturales."),
    ACTIVIDADES_DE_SITIOS_Y_MONUMENTOS_HISTORICOS_Y_OTROS_ATRACTIVOS_TURISTICOS("9102", "Actividades de sitios y monumentos históricos y otros atractivos turísticos."),
    ACTIVIDADES_DE_JARDINES_BOTANICOS_ZOOLOGICOS_Y_RESERVAS_NATURALES("9103", "Actividades de jardines botánicos, zoológicos y reservas naturales."),
    ORGANIZACION_Y_FUNCIONAMIENTO_DE_LOTERIAS("9200", "Organización y funcionamiento de loterías."),
    ACTIVIDADES_DE_TRABAJO_DE_CLUBES_DEPORTIVOS("9311", "Actividades de trabajo de clubes deportivos."),
    ACTIVIDADES_DE_APOYO_AL_DEPORTE("9312", "Actividades de apoyo al deporte."),
    ACTIVIDADES_DE_GIMNASIOS("9313", "Actividades de gimnasios."),
    OTRAS_ACTIVIDADES_DEPORTIVAS("9319", "Otras actividades deportivas."),
    ACTIVIDADES_DE_PARQUES_RECREATIVOS_Y_PARQUES_DE_ATRACCIONES("9321", "Actividades de parques recreativos y parques de atracciones."),
    ACTIVIDADES_DE_APOSTADORES("9411", "Actividades de apostadores."),
    ACTIVIDADES_DE_CASINOS("9412", "Actividades de casinos."),
    ACTIVIDADES_DE_BINGOS_Y_CORREDORES_DE_APUESTAS("9413", "Actividades de bingos y corredores de apuestas."),
    ACTIVIDADES_DE_OTROS_JUEGOS_DE_AZAR_Y_APUESTA_NCP("9420", "Actividades de otros juegos de azar y apuesta n.c.p."),
    RESTAURANTES_BARES_Y_CANTINAS("9511", "Restaurantes, bares y cantinas."),
    CAFETERIAS("9512", "Cafeterías."),
    ACTIVIDADES_DE_SERVICIO_DE_COMIDA_PARA_EVENTOS_Y_OTRAS_ACTIVIDADES_DE_SERVICIO_DE_COMIDA("9520", "Actividades de servicio de comida para eventos y otras actividades de servicio de comida."),
    ACTIVIDADES_DE_SERVICIO_DE_BEVIDAS("9530", "Actividades de servicio de bebidas."),
    ACTIVIDADES_DE_ALOJAMIENTO("9601", "Actividades de alojamiento."),
    ACTIVIDADES_DE_LAVANDERIAS_Y_LIMPIEZA_DE_PRENDAS_LAVADO_TINTORERIA_Y_LIMPIEZA_DE_PIELES("9602", "Actividades de lavanderías y limpieza de prendas (lavado, tintorería y limpieza de pieles)."),
    PELUQUERIA_Y_OTRAS_ACTIVIDADES_DE_TRATAMIENTO_DE_BELLEZA("9603", "Peluquería y otras actividades de tratamiento de belleza."),
    POMPAS_FUNE_BRES("9700", "Pompas fúnebres."),
    ACTIVIDADES_DE_OTROS_SERVICIOS_PERSONALES_NCP("9810", "Actividades de otros servicios personales n.c.p."),
    OTRAS_ACTIVIDADES_DE_SERVICIOS_NCP("9820", "Otras actividades de servicios n.c.p."),
    PERSONAS_NATURALES("9998","Personas naturales o sucesiones ilíquidas cuyos ingresos provienen de intereses, descuentos, beneficios, ganancias, utilidades y en general, todo cuanto represente rendimiento de capital o diferencia entre el valor invertido o aportado, y el valor futuro y/o pagado o abonado al aportante o inversionista."),
    CLASIFICACION_DESCONOCIDA("9999","Otras Clasificaciones");

    private final String codigo;
    private final String descripcion;

    Actividades(String codigo, String descripcion) {
        this.codigo = codigo;
        this.descripcion = descripcion;
    }

    public String getCodigo() {
        return codigo;
    }

    public String getDescripcion() {
        return descripcion;
    }

}
